# Generated by Django 5.0 on 2023-12-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='total_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
