# Generated by Django 5.0 on 2023-12-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0002_alter_material_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='markup',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
