# Generated by Django 5.0 on 2024-01-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0005_product_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(through='CLEAR.Product_Material', to='CLEAR.material'),
        ),
    ]
