# Generated by Django 5.0 on 2024-01-11 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0008_alter_order_delivery_date_alter_order_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.product')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.item')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.material')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='materials',
            field=models.ManyToManyField(through='CLEAR.Item_Material', to='CLEAR.material'),
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.order')),
            ],
        ),
    ]
