# Generated by Django 5.0 on 2024-01-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0009_item_item_material_item_materials_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
