# Generated by Django 5.0 on 2024-01-16 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0010_alter_order_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.item'),
        ),
    ]
