# Generated by Django 5.0 on 2024-02-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0014_alter_order_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('unit', models.CharField(choices=[('PC', 'per piece'), ('IN', 'per inch')], default='PC', max_length=2)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Global_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bespoke_rate', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.accessory')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Textile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bespoke_rate', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(default='In-queue', max_length=50)),
                ('file_date', models.DateField()),
                ('completion_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialKey',
            fields=[
                ('material_key', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('buffer', models.FloatField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.component')),
            ],
        ),
        migrations.CreateModel(
            name='Textile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('unit', models.CharField(choices=[('FT', 'per sq/ft'), ('IN', 'per inch'), ('M', 'per meter')], default='FT', max_length=2)),
                ('stock', models.FloatField()),
                ('material_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.materialkey')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('edit_reason', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Textile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('textile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.textile')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='product_material',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product_material',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.AddField(
            model_name='product',
            name='labor_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='misc_margin',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_margin',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='total_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item_accessory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='accessories',
            field=models.ManyToManyField(through='CLEAR.Item_Accessory', to='CLEAR.accessory'),
        ),
        migrations.AddField(
            model_name='item_textile',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.item'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.job_order'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='material_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.materialkey'),
        ),
        migrations.AddField(
            model_name='product_accessory',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.accessory'),
        ),
        migrations.AddField(
            model_name='product_accessory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='accessories',
            field=models.ManyToManyField(through='CLEAR.Product_Accessory', to='CLEAR.accessory'),
        ),
        migrations.AddField(
            model_name='product_component',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.product'),
        ),
        migrations.AddField(
            model_name='product_component',
            name='textile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.textile'),
        ),
        migrations.AddField(
            model_name='item_textile',
            name='textile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.textile'),
        ),
        migrations.AddField(
            model_name='item',
            name='textiles',
            field=models.ManyToManyField(through='CLEAR.Item_Textile', to='CLEAR.textile'),
        ),
        migrations.AddField(
            model_name='product',
            name='textiles',
            field=models.ManyToManyField(through='CLEAR.Product_Component', to='CLEAR.textile'),
        ),
        migrations.AddField(
            model_name='transaction_accessory',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.accessory'),
        ),
        migrations.AddField(
            model_name='transaction_accessory',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='accessories',
            field=models.ManyToManyField(through='CLEAR.Transaction_Accessory', to='CLEAR.accessory'),
        ),
        migrations.AddField(
            model_name='transaction_textile',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='textiles',
            field=models.ManyToManyField(through='CLEAR.Transaction_Textile', to='CLEAR.textile'),
        ),
        migrations.DeleteModel(
            name='Item_Material',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Product_Material',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
