# Generated by Django 5.0 on 2024-02-17 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0015_accessory_account_component_global_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(db_column='product_number', on_delete=django.db.models.deletion.CASCADE, to='CLEAR.product'),
        ),
        migrations.AlterField(
            model_name='item_accessory',
            name='item',
            field=models.ForeignKey(db_column='product_number', on_delete=django.db.models.deletion.CASCADE, to='CLEAR.item'),
        ),
        migrations.AlterField(
            model_name='item_textile',
            name='item',
            field=models.ForeignKey(db_column='product_number', on_delete=django.db.models.deletion.CASCADE, to='CLEAR.item'),
        ),
    ]
