# Generated by Django 5.0.2 on 2024-02-21 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0016_alter_item_product_alter_item_accessory_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='stock',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='textile',
            name='stock',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
