# Generated by Django 5.0.2 on 2024-02-21 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0017_alter_accessory_stock_alter_textile_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='textile',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
