# Generated by Django 5.0.2 on 2024-02-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0017_alter_accessory_cost_alter_accessory_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item_accessory',
            name='bespoke_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item_accessory',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item_textile',
            name='bespoke_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item_textile',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='labor_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_margin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_accessory',
            name='accessory_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_component',
            name='buffer',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product_component',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product_component',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_component',
            name='width',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='textile',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='textile',
            name='stock',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction_accessory',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction_textile',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
