# Generated by Django 5.0.2 on 2024-02-19 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0018_alter_accessory_cost_alter_accessory_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='cost',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='textile',
            name='cost',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='textile',
            name='stock',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
