# Generated by Django 5.0 on 2024-03-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0019_alter_accessory_name_alter_textile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_component',
            name='buffer',
            field=models.FloatField(null=True),
        ),
    ]
