# Generated by Django 5.0 on 2024-03-30 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0020_alter_product_component_buffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('edit_reason', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction_textile',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction_accessory',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction_accessory',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='transaction_textile',
            name='textile',
        ),
        migrations.AlterField(
            model_name='textile',
            name='unit',
            field=models.CharField(choices=[('FT', 'per sq/ft'), ('IN', 'per sq/in'), ('M', 'per sq/m')], default='FT', max_length=2),
        ),
        migrations.CreateModel(
            name='StockIn_Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.accessory')),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.stockin')),
            ],
        ),
        migrations.AddField(
            model_name='stockin',
            name='accessories',
            field=models.ManyToManyField(through='CLEAR.StockIn_Accessory', to='CLEAR.accessory'),
        ),
        migrations.CreateModel(
            name='StockIn_Textile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.stockin')),
                ('textile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLEAR.textile')),
            ],
        ),
        migrations.AddField(
            model_name='stockin',
            name='textiles',
            field=models.ManyToManyField(through='CLEAR.StockIn_Textile', to='CLEAR.textile'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Transaction_Accessory',
        ),
        migrations.DeleteModel(
            name='Transaction_Textile',
        ),
    ]
