# Generated by Django 5.0.2 on 2024-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0020_alter_product_labor_time_alter_product_misc_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='labor_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='misc_margin',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_margin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
