# Generated by Django 5.0.2 on 2024-02-20 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0021_alter_product_labor_time_alter_product_misc_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='textile',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='textile',
            name='stock',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
