# Generated by Django 5.0 on 2024-04-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0021_stockin_remove_transaction_textile_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin_accessory',
            name='cost',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockin_textile',
            name='cost',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
