# Generated by Django 5.0.2 on 2024-02-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0022_alter_accessory_cost_alter_accessory_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='textile',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
