# Generated by Django 5.0.2 on 2024-02-20 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0023_alter_accessory_cost_alter_textile_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='stock',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
