# Generated by Django 5.0 on 2024-04-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0024_alter_stockin_textile_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='job_order',
            old_name='completion_date',
            new_name='finish_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='total_cost',
            new_name='calc_price',
        ),
        migrations.AddField(
            model_name='job_order',
            name='customer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job_order',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_update',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='labor_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='misc_margin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_margin',
            field=models.FloatField(null=True),
        ),
    ]
