# Generated by Django 5.0 on 2024-04-29 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0025_store_rename_completion_date_job_order_finish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='job_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CLEAR.job_order'),
            preserve_default=False,
        ),
    ]
