# Generated by Django 5.0.2 on 2024-02-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0026_alter_accessory_stock_alter_textile_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='textile',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=1000000, null=True),
        ),
    ]
