# Generated by Django 5.0 on 2024-04-30 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0027_rename_finish_date_job_order_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='job_order',
        ),
        migrations.AddField(
            model_name='job_order',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CLEAR.store'),
            preserve_default=False,
        ),
    ]
