# Generated by Django 5.0 on 2024-04-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0028_remove_store_job_order_job_order_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Outlet',
        ),
        migrations.RenameField(
            model_name='outlet',
            old_name='store_name',
            new_name='outlet_name',
        ),
    ]
