# Generated by Django 5.0 on 2024-05-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0029_rename_store_outlet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_order',
            old_name='store',
            new_name='outlet',
        ),
        migrations.AddField(
            model_name='job_order',
            name='total_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
