# Generated by Django 5.0 on 2024-05-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0030_rename_store_job_order_outlet_job_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_order',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
