# Generated by Django 5.0 on 2024-05-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0032_alter_stockin_accessory_cost_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Global_Value',
            new_name='Financial_Value',
        ),
    ]
