# Generated by Django 5.0 on 2024-05-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0034_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='labor_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='misc_margin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_margin',
            field=models.FloatField(),
        ),
    ]
