# Generated by Django 5.0.4 on 2024-05-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0035_alter_product_labor_time_alter_product_misc_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('product_manager', 'Product Manager')], max_length=50),
        ),
    ]
