# Generated by Django 5.0.2 on 2024-05-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0037_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
