# Generated by Django 5.0.2 on 2024-05-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLEAR', '0038_remove_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
